### ISSUE TITLE
Just not working

### ISSUE THREAD

**Issue by cloydlau** [nielsboogaard/filepond-plugin-image-overlay#7]
I did exactly as Quick Start said but there's no 'eye' icon in front of the filename.
I tried vue-filepond@6.0.2 and filepond@4.13.7 itself, both failed.

**Comment by cloydlau** [comment]
The another plugin 'filepond-plugin-media-preview' is working pretty well by the way.

**Comment by berniegreen** [comment]
@cloydlau looks like he forgot to mention in the readme to include the css file. Try the below:

`import 'filepond-plugin-image-overlay/dist/filepond-plugin-image-overlay.css'`

**Comment by cloydlau** [comment]
@berniegreen thanks, that will do
